### PR TITLE
encode byte slices using hex

### PR DESCRIPTION
**Pull request by cfromknecht**

### CODE REVIEW

**Review by joostjager — COMMENTED** [review]
Concept ACK. Seems to be the easiest way to reduce maintenance cost and bug potential on `lncli`. This repo is big, but we only need to look at it once instead of with every change in `lncli`.

I do think it would be good to rename the repo to something like `protobuf-hex-display` to make it really clear that this is not for normal protobuf usage.

**Comment by cfromknecht** [comment]
> I do think it would be good to rename the repo to something like protobuf-hex-display to make it really clear that this is not for normal protobuf usage.

Name has been updated, and [upstream PR](https://github.com/lightningnetwork/lnd/pull/3647) is passing.

**Review by halseth — APPROVED** [review]
ACK. I've only looked at our specific changes, not audited the whole monster :P

**Review by joostjager — APPROVED** [review]
Yes, let's do it and just pretend this repo does not exist

**Pull request merged**
